name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  android-lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Lint Tools
        run: ./gradlew lintDebug
      - name: Upload Lint report
        uses: actions/upload-artifact@v1
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html
