name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]





jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
      - uses: actions/checkout@v2

      - name: Run Lint
      - uses: ./gradlew lintDebug
      - name: upload lint report
      - uses: actions/upload-artifact@v1

      with:
        name: index.html
        path: app/build/reports/lint-reports-debug.html
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
